export const domElements = {
  searchFriends: document.querySelector('.friends_list'),
  findFriends: document.querySelector('.find-friends'),
  loader: document.querySelector('.loader'),
  friendsList: document.querySelector('.friends-list'),
  postsList: document.querySelector('.posts'),
  postForm: document.querySelector('.post-form'),
  postInput: document.querySelector('.post-input'),
  postSubmitBtn: document.querySelector('.submit-btn'),
  nav: document.querySelector('.navigation'),
  main: document.querySelector('.main'),
  commentParagraf: document.querySelector('.comments-paragraph'),
  postItem: document.querySelector('.post-item'),
  commentsListt: document.querySelector('.comment-list'),
};
